name: "test azure"
on:
  workflow_dispatch:

jobs:  
  deploy-using-azure-pipelines:
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger an Azure Pipeline to deploy the app to PRODUCTION'
      uses: Azure/pipelines@releases/v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/mseng/VSIoT'
        azure-pipeline-name: 'Build Function Extension Release Artifacts' 
        azure-devops-token: '${{ secrets.ADO_PAT }}'