name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha or rc)"
        required: true
        default: "alpha"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc
      
      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'wenytang-ms-123'
          git config --global user.email 'wenytang@wenytang.onmicrosoft.com'

      - name: release prerelease npm packages to npmjs.org
        id: version-change
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=${{github.event.inputs.preid }}  --yes
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD | xargs)"

      - name: output versoin check
        run: |
          echo ${{ steps.version-change.outputs.CHANGED }}
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' > ./template-tags.txt

      - name: Update Template Tag list Release
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'test1@') }}
        uses: ncipollo/release-action@v1.7.3
        with:
          artifacts: ./packages/test1/*.zip
          name: $(tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test1@')
          body: 'Release to maintain template tag list.'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: $(tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test1@')
          allowUpdates: true  

      - name: check test1
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'test1@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test1@'

      - name: check test2
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'test2@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test2@'
      
      - name: check test3
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'test3@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test3@'

      - name: check simple
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'simple@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'simple@'

      - name: output
        run: |
          less ./template-tags.txt