name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha or rc)"
        required: true
        default: "alpha"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x

      - name: Build SimpleAuth
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
        working-directory: ./packages/simpleauth
      
      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'wenytang-ms-123'
          git config --global user.email 'wenytang@wenytang.onmicrosoft.com'

      - name: release prerelease npm packages to npmjs.org
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=${{github.event.inputs.preid }}  --yes

      - name: output versoin check
        id: version-change
        run: |
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD | xargs)"
          echo "::set-output name=TEST1_VERSION::$(git tag --points-at HEAD | grep test1)"

      - name: check test1
        if: ${{ steps.version-change.outputs.TEST1_VERSION }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test1@'

      - name: check test2
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'test2@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test2@'
      
      - name: check test3
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'test3@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'test3@'

      - name: check simple
        if: ${{ contains(steps.version-change.outputs.CHANGED, 'templates@') }}
        run: |
          tr ' ' '\n' <<< '${{ steps.version-change.outputs.CHANGED }}' | grep 'simple@'
