name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha or rc)"
        required: true
        default: "alpha"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc
      
      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'wenytang-ms-123'
          git config --global user.email 'wenytang@wenytang.onmicrosoft.com'

      - name: release prerelease npm packages to npmjs.org
        id: version-release
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=${{github.event.inputs.preid }}  --yes
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD | xargs)"

      - name: output versoin check
        run: |
          echo ${{ steps.version-release.outputs.CHANGED }}
          echo $(echo ${{ steps.version-release.outputs.CHANGED }} | tr ' ' '\n')

      - name: check test1
        if: ${{ contains(steps.version-release.outputs.CHANGED, 'test1@') }}
        run: |
          echo "test1"
          echo $(echo ${{ steps.version-release.outputs.CHANGED }} | tr ' ' '\n'| grep 'test1@')

      - name: check test2
        if: ${{ contains(steps.version-release.outputs.CHANGED, 'test2@') }}
        run: |
          echo "test2"
          echo $(echo ${{ steps.version-release.outputs.CHANGED }} | tr ' ' '\n'| grep 'test2@')
      
      - name: check test3
        if: ${{ contains(steps.version-release.outputs.CHANGED, 'test3@') }}
        run: |
          echo "test3"
          echo $(echo ${{ steps.version-release.outputs.CHANGED }} | tr ' ' '\n'| grep 'test3@')

      - name: check simple
        if: ${{ contains(steps.version-release.outputs.CHANGED, 'simple@') }}
        run: |
          echo "simnple"
          echo $(echo ${{ steps.version-release.outputs.CHANGED }} | tr ' ' '\n'| grep 'simple@')
