name: CD

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha or rc)"
        required: true
        default: "alpha"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc
      
      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'wenytang-ms-123'
          git config --global user.email 'wenytang@wenytang.onmicrosoft.com'

      - id: check
        run: |
          echo "lerna diff simple"

      - name: release prerelease npm packages to npmjs.org
        id: version-release
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid=${{github.event.inputs.preid }}  --yes
          echo "::set-output name=CHANGED::$(git tag --points-at HEAD)"

      - name: check
        if: ${{ contains(steps.version-release.outputs.CHANGED, 'test1') }}
        run: |
          echo "123123"

