name: CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: "which version to bump(major, minor, patch, premajor, preminor, prepatch, prerelease)"
        required: true
        default: "prerelease"
      preid:
        description: "preid name(alpha or rc)"
        required: false
        default: "alpha"
      force:
        description: "force release even if no update(set --force-publish if necessary)"
        required: false
        default: ""
  schedule:
    - cron: "0 8 * * *"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: validate branch
        if: ${{ (github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/maven') || (github.ref == 'refs/heads/develop' && (!startsWith(github.event.inputs.version, 'pre') || github.event.inputs.preid != 'alpha')) || (github.ref == 'refs/heads/maven' && startsWith(github.event.inputs.version, 'pre') && github.event.inputs.preid != 'rc') }}
        run: |
          exit 1

      - name: Checkout maven branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: maven

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup npm registry
        run: |
          echo "${{ secrets.NPMRC }}" > ~/.npmrc
      
      - name: Setup project
        run: |
          npm run setup

      - name: Setup git
        run: |
          git config --global user.name 'wenytang-ms-123'
          git config --global user.email 'wenytang@wenytang.onmicrosoft.com'

      - name: release prerelease npm packages to npmjs.org
        if: ${{ startsWith(github.event.inputs.version, 'pre') }}
        run: |
          npx lerna publish --no-private --preid=${{github.event.inputs.preid }} --dist-tag=${{github.event.inputs.preid }} ${{ github.event.inputs.version }} --yes ${{ github.event.inputs.force }}
