name: CI

on:
  pull_request_target:
    branches:
      - main
      - maven
      - dev 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup
        run: |
          npm run setup

      - name: echo
        run: |
          less package.json