name: Delete tags and assets

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        default: "alpha"
  
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.github_token }}
          tag: ${{ github.event.inputs.tag_name }} # This may also be of the form 'refs/tags/staging'
          assets: |
            changelog.txt
            *.zip
            *.tar.gz
            Source code
