name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-uncommit:
    if: ${{ github.event_name == 'pull_request' && github.pull_request.action != 'edited' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        run: |
          echo ${github.event_name}