name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup project
        run: |
          npm run setup

  check-format:
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'edited' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: prettier check files in PR on Fork
        if: ${{ github.event.pull_request.head.repo.full_name != 'wenytang-ms-123/testavc' }}
        run: |
          git remote -v
          git remote add upstream https://github.com/wenytang-ms-123/testavc.git
          git remote -v
          git fetch upstream ${{ github.event.pull_request.base.ref }}
          VAR=$(realpath .github/scripts/lint-pr.sh)
          npx lerna exec -- bash $VAR upstream/${{ github.event.pull_request.base.ref }}

      - name: prettier check files in PR on local
        if: ${{ github.event.pull_request.head.repo.full_name == 'wenytang-ms-123/testavc' }}
        run: |
          VAR=$(realpath .github/scripts/lint-pr.sh)
          npx lerna exec -- bash $VAR origin/${{ github.event.pull_request.base.ref }}

      - name: Check if there are changes
        id: changes
        run: |
          git add .
          VAR=$(git diff --cached --name-only)
          if [ ! -z "$VAR" ]
          then 
            echo "There may be some unformatted files in your PR, please run these commands on Git Bash terminal: \
            1. VAR=$(realpath .github/scripts/lint-pr.sh) \
            2. npx lerna exec – bash $VAR ${your-PR-target-branch}"
            exit 1
          fi
